server:
  port: 8089
spring:
    application:
        name: currency
    datasource:
        url: jdbc:postgresql://192.168.99.100:5432/postgres
        username: postgres
        password: postgres
    jpa:
        generate-ddl: true
        properties.hibernate.temp.use_jdbc_metadata_defaults: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/