server:
  port: 8091

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#      - id: baeldung
#        uri: baeldung.com
#      - id: myOtherRouting
#        uri: localhost:9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

order:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000

ribbon:
  eureka:
     enabled: true
  eager-load:
    enabled: true