server:
  port: 8090
spring:
    application:
        name: order
    datasource:
        initialization-mode: always
#        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
        url: jdbc:postgresql://192.168.99.100:5432/postgres
        username: postgres
        password: postgres
        schemaUsername: postgres
        schemaPassword: postgres
        dataUsername: postgres
        dataPassword: postgres
#        schema: classpath:schema.sql
#        data: classpath:data.sql
#       driver-class-name: org.h2.Driver
    jpa:
        generate-ddl: false
        generate-ddl-auto: false
        properties.hibernate.temp.use_jdbc_metadata_defaults: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/